[server]
headless = true
enableCORS = false
enableXsrfProtection = true
address = "0.0.0.0"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#818CF8"
backgroundColor = "#090A10"
secondaryBackgroundColor = "#121324"
textColor = "#F8FAFC"
